# config/packages/easy_admin.yaml
easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
      - '@VichUploader/Form/field.html.twig'
      - '@FMElfinder/Form/elfinder_widget.html.twig'
