vich_uploader:
    db_driver: orm

    mappings:
        article_images:
          uri_prefix: /images/article
          upload_destination: '%kernel.project_dir%/public/images/article'
        pronostics_images:
          uri_prefix: /images/pronostics
          upload_destination: '%kernel.project_dir%/public/images/pronostics'
        forum_images:
          uri_prefix: /images/forum
          upload_destination: '%kernel.project_dir%/public/images/forum'
        user_images:
          uri_prefix: /images/users
          upload_destination: '%kernel.project_dir%/public/images/users'
          inject_on_load: faux
          delete_on_update: vrai
          delete_on_remove: faux

